Enhanced Support for PRs
Signed-off-by: Sushrut1101 <guptasushrut@gmail.com>

diff --git a/.cirrus.yml b/.cirrus.yml
--- a/.cirrus.yml
+++ b/.cirrus.yml
@@ -2,32 +2,12 @@ env:
     # OrangeFox Sync Repository
     FOX_SYNC: https://gitlab.com/OrangeFox/sync.git
 
-    # Device
-    FOX_BRANCH: fox_9.0
-    DT_LINK: https://gitlab.com/OrangeFox/device/beryllium.git -b fox_9.0
-    DEVICE: beryllium
-    OEM: xiaomi
-    TARGET: recoveryimage
-
-    DT_PATH: device/$OEM/$DEVICE
-    OUTPUT: OrangeFox*.zip
-
-    # Extra Command
-    EXTRA_CMD: git clone https://github.com/OrangeFoxRecovery/Avatar.git misc
-
-    # Not Recommended to Change
-    SYNC_PATH: $HOME/work # Full (absolute) path. Use "$HOME" instead of "~".
-    USE_CCACHE: 1
-    CCACHE_SIZE: 50G
-    CCACHE_DIR: $HOME/work/.ccache
-    J_VAL: 16
-
-    # Cirrus Specific Vars (Do *NOT* Change)
-    CIRRUS_SHELL: bash
-
     # Telegram
     TG_CHAT_ID: ENCRYPTED[0003e1cf5276424a5b2afb8c6a39f2d830864e8555b37220bd3bf173f3ef5b8769ab98425d96a76adf64b18241c940dd]
     TG_TOKEN: ENCRYPTED[03de4105db5d23ec42490965c0a0f79217c1e3366cb152bd9d9a045e22586eba675615e1f08bf1aea3e860d499efde60]
+
+    # Cirrus Specific Vars (Do *NOT* Change)
+    CIRRUS_SHELL: bash
 
 task:
   name: "Recovery Build"
@@ -38,12 +18,21 @@ task:
       cpu: 8
       memory: 32G
 
+  Checks_script:
+      - if [ ! -z $(cat vars.sh | grep "TG") ]; then
+            echo "ERROR - You Cannot Set *TG* Vars in your vars.sh"
+            exit 1
+        fi
+
+  Vars_script:
+      - source vars.sh
+
   Sync_script:
-      - bash sync.sh
+      - curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/sync.sh | bash
 
   Build_script:
-      - bash build.sh
+      - curl -sL https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/build.sh | bash
 
   Upload_script:
       - export TIMEOUT=43200 # Link timeout (in minutes)
-      - bash upload.sh
+      - curl https://raw.githubusercontent.com/OrangeFoxRecovery/OrangeFox-CI/fox/upload.sh | bash
